'use strict';

/**
 * Upload routes
 *
 * POST /api/upload/consumo  — upload & parse legacy XLS consumption report
 * POST /api/upload/vales    — upload & parse HTML vales report
 */

const express = require('express');
const multer  = require('multer');

const auth           = require('../middleware/auth');
const { supabaseAdmin } = require('../db/supabase');
const { parseConsumo } = require('../services/consumoParser');
const { parseVales }   = require('../services/valesParser');

const router  = express.Router();
const storage = multer.memoryStorage();
const upload  = multer({
  storage,
  limits: { fileSize: 20 * 1024 * 1024 }, // 20 MB
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Ensure fechamento exists and return it. */
async function getFechamento(fechamento_id) {
  const { data, error } = await supabaseAdmin
    .from('fechamentos')
    .select('*')
    .eq('id', fechamento_id)
    .single();
  if (error || !data) return null;
  return data;
}

/** Save a document reference. */
async function saveDocumento(fechamento_id, tipo, nome_arquivo, tamanho) {
  await supabaseAdmin.from('documentos').insert({
    fechamento_id,
    tipo,
    nome_arquivo,
    tamanho,
  });
}

/**
 * Persist pendencias generated by a parser result.
 * Clears existing pendencias of the same type for this fechamento first,
 * then inserts new ones.
 */
async function savePendencias(fechamento_id, parserResults, tipo_doc) {
  const pendencias = [];

  for (const item of parserResults.blocked) {
    pendencias.push({
      fechamento_id,
      tipo: 'proibido',
      descricao: `Nome bloqueado encontrado no ${tipo_doc}: "${item.originalName}" (normalizado: ${item.normalizedName})`,
      nome_original: item.originalName,
      valor: item.valor || null,
    });
  }

  for (const item of parserResults.ambiguous) {
    const opcoes = (item.options || []).map(o => o.nome).join(', ');
    pendencias.push({
      fechamento_id,
      tipo: 'ambiguo',
      descricao: `Nome ambíguo no ${tipo_doc}: "${item.originalName}" — opções: ${opcoes}`,
      nome_original: item.originalName,
      valor: item.valor || null,
    });
  }

  for (const item of parserResults.notFound) {
    pendencias.push({
      fechamento_id,
      tipo: 'nao_encontrado',
      descricao: `Funcionário não encontrado no ${tipo_doc}: "${item.originalName}" (normalizado: ${item.normalizedName})`,
      nome_original: item.originalName,
      valor: item.valor || null,
    });
  }

  if (pendencias.length > 0) {
    await supabaseAdmin.from('pendencias').insert(pendencias);
  }
}

// ---------------------------------------------------------------------------
// POST /api/upload/consumo
// ---------------------------------------------------------------------------
router.post('/consumo', auth, upload.single('file'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'Nenhum arquivo enviado.' });
    }

    const { fechamento_id } = req.body;
    if (!fechamento_id) {
      return res.status(400).json({ error: 'fechamento_id é obrigatório.' });
    }

    const fechamento = await getFechamento(fechamento_id);
    if (!fechamento) {
      return res.status(404).json({ error: 'Fechamento não encontrado.' });
    }
    if (fechamento.status === 'aprovado') {
      return res.status(409).json({ error: 'Fechamento já aprovado. Não é possível alterar.' });
    }

    // Parse
    const results = parseConsumo(req.file.buffer);

    // Save document reference
    await saveDocumento(fechamento_id, 'consumo', req.file.originalname, req.file.size);

    // Save pendencias
    await savePendencias(fechamento_id, results, 'consumo');

    // Upsert lancamentos (consumo)
    for (const [fidStr, entry] of Object.entries(results.matched)) {
      const funcionario_id = parseInt(fidStr, 10);
      await supabaseAdmin
        .from('lancamentos')
        .upsert(
          { fechamento_id, funcionario_id, consumo: entry.total },
          { onConflict: 'fechamento_id,funcionario_id', ignoreDuplicates: false }
        );
    }

    return res.json({
      matched:   Object.values(results.matched),
      blocked:   results.blocked,
      ambiguous: results.ambiguous,
      notFound:  results.notFound,
      ignored:   results.ignored,
      rawTotal:  results.rawTotal,
    });
  } catch (err) {
    console.error('[upload/consumo]', err);
    return res.status(500).json({ error: err.message || 'Erro ao processar consumo.' });
  }
});

// ---------------------------------------------------------------------------
// POST /api/upload/vales
// ---------------------------------------------------------------------------
router.post('/vales', auth, upload.single('file'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'Nenhum arquivo enviado.' });
    }

    const { fechamento_id } = req.body;
    if (!fechamento_id) {
      return res.status(400).json({ error: 'fechamento_id é obrigatório.' });
    }

    const fechamento = await getFechamento(fechamento_id);
    if (!fechamento) {
      return res.status(404).json({ error: 'Fechamento não encontrado.' });
    }
    if (fechamento.status === 'aprovado') {
      return res.status(409).json({ error: 'Fechamento já aprovado. Não é possível alterar.' });
    }

    // Parse HTML (multer buffer → string)
    const htmlContent = req.file.buffer.toString('utf8');
    const results = parseVales(htmlContent);

    // Save document reference
    await saveDocumento(fechamento_id, 'vales', req.file.originalname, req.file.size);

    // Save pendencias
    await savePendencias(fechamento_id, results, 'vales');

    // Upsert lancamentos (vales)
    for (const [fidStr, entry] of Object.entries(results.matched)) {
      const funcionario_id = parseInt(fidStr, 10);
      await supabaseAdmin
        .from('lancamentos')
        .upsert(
          { fechamento_id, funcionario_id, vales: entry.total },
          { onConflict: 'fechamento_id,funcionario_id', ignoreDuplicates: false }
        );
    }

    return res.json({
      matched:   Object.values(results.matched),
      blocked:   results.blocked,
      ambiguous: results.ambiguous,
      notFound:  results.notFound,
      ignored:   results.ignored,
      rawTotal:  results.rawTotal,
    });
  } catch (err) {
    console.error('[upload/vales]', err);
    return res.status(500).json({ error: err.message || 'Erro ao processar vales.' });
  }
});

module.exports = router;
